import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('electronAPI', {
  ping: () => ipcRenderer.invoke('ping'),
  auth: {
    getBootstrap: () => ipcRenderer.invoke('auth:getBootstrap'),
    register: (data: { email: string; name: string; password: string }) =>
      ipcRenderer.invoke('auth:register', data),
    login: (data: { email: string; password: string }) => ipcRenderer.invoke('auth:login', data),
    logout: () => ipcRenderer.invoke('auth:logout'),
    forgotPassword: (email: string) => ipcRenderer.invoke('auth:forgotPassword', email),
    resetPassword: (data: { token: string; newPassword: string }) =>
      ipcRenderer.invoke('auth:resetPassword', data),
    listUsers: () => ipcRenderer.invoke('auth:listUsers'),
    createUser: (data: { email: string; name: string; password: string; role: 'admin' | 'profesor' }) =>
      ipcRenderer.invoke('auth:createUser', data),
    updateUserRole: (userId: number, role: 'admin' | 'profesor') =>
      ipcRenderer.invoke('auth:updateUserRole', userId, role),
    adminSetPassword: (userId: number, newPassword: string) =>
      ipcRenderer.invoke('auth:adminSetPassword', userId, newPassword),
    deleteUser: (userId: number) => ipcRenderer.invoke('auth:deleteUser', userId),
    getMailSettings: () => ipcRenderer.invoke('auth:getMailSettings'),
    setMailSettings: (data: { url: string; secret: string }) => ipcRenderer.invoke('auth:setMailSettings', data),
    getUserPeriodVigencia: (userId: number) => ipcRenderer.invoke('auth:getUserPeriodVigencia', userId),
    setUserPeriodVigencia: (userId: number, periodId: number, status: 'active' | 'inactive') =>
      ipcRenderer.invoke('auth:setUserPeriodVigencia', userId, periodId, status),
  },
  personLookup: {
    getSettings: () => ipcRenderer.invoke('personLookup:getSettings'),
    setSettings: (data: { url: string; secret: string }) => ipcRenderer.invoke('personLookup:setSettings', data),
    query: (cedula: string) => ipcRenderer.invoke('personLookup:query', cedula),
  },
  schools: {
    getAll: () => ipcRenderer.invoke('schools:getAll'),
    getById: (id: number) => ipcRenderer.invoke('schools:getById', id),
    create: (data: any) => ipcRenderer.invoke('schools:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('schools:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('schools:delete', id),
  },
  groups: {
    getAll: () => ipcRenderer.invoke('groups:getAll'),
    getById: (id: number) => ipcRenderer.invoke('groups:getById', id),
    getBySchoolId: (schoolId: number) => ipcRenderer.invoke('groups:getBySchoolId', schoolId),
    create: (data: any) => ipcRenderer.invoke('groups:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('groups:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('groups:delete', id),
  },
  courses: {
    getAll: () => ipcRenderer.invoke('courses:getAll'),
    getById: (id: number) => ipcRenderer.invoke('courses:getById', id),
    getByGroupId: (groupId: number) => ipcRenderer.invoke('courses:getByGroupId', groupId),
    getByPeriodId: (periodId: number) => ipcRenderer.invoke('courses:getByPeriodId', periodId),
    create: (data: any) => ipcRenderer.invoke('courses:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('courses:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('courses:delete', id),
  },
  students: {
    getAll: () => ipcRenderer.invoke('students:getAll'),
    getById: (id: number) => ipcRenderer.invoke('students:getById', id),
    getByIdentifier: (identifier: string) => ipcRenderer.invoke('students:getByIdentifier', identifier),
    search: (query: string) => ipcRenderer.invoke('students:search', query),
    create: (data: any) => ipcRenderer.invoke('students:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('students:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('students:delete', id),
  },
  academicYears: {
    getAll: () => ipcRenderer.invoke('academicYears:getAll'),
    getById: (id: number) => ipcRenderer.invoke('academicYears:getById', id),
    create: (data: any) => ipcRenderer.invoke('academicYears:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('academicYears:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('academicYears:delete', id),
  },
  studentCourses: {
    getByCourseId: (courseId: number) => ipcRenderer.invoke('studentCourses:getByCourseId', courseId),
    getByStudentId: (studentId: number) => ipcRenderer.invoke('studentCourses:getByStudentId', studentId),
    getStudentsByCourseIds: (courseIds: number[]) => ipcRenderer.invoke('studentCourses:getStudentsByCourseIds', courseIds),
    create: (data: any) => ipcRenderer.invoke('studentCourses:create', data),
    createMany: (data: any[]) => ipcRenderer.invoke('studentCourses:createMany', data),
    delete: (id: number) => ipcRenderer.invoke('studentCourses:delete', id),
    deleteByStudentAndCourse: (studentId: number, courseId: number) => ipcRenderer.invoke('studentCourses:deleteByStudentAndCourse', studentId, courseId),
    exists: (studentId: number, courseId: number) => ipcRenderer.invoke('studentCourses:exists', studentId, courseId),
  },
  periods: {
    getAll: () => ipcRenderer.invoke('periods:getAll'),
    getById: (id: number) => ipcRenderer.invoke('periods:getById', id),
    getByYear: (year: string) => ipcRenderer.invoke('periods:getByYear', year),
    getByType: (type: string) => ipcRenderer.invoke('periods:getByType', type),
    getByTypeAndYear: (type: string, year: string) => ipcRenderer.invoke('periods:getByTypeAndYear', type, year),
    getByAcademicYearId: (academicYearId: number) =>
      ipcRenderer.invoke('periods:getByAcademicYearId', academicYearId),
    create: (data: any) => ipcRenderer.invoke('periods:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('periods:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('periods:delete', id),
  },
  files: {
    selectFile: (options: any) => ipcRenderer.invoke('files:selectFile', options),
    readImageAsBase64: (filePath: string) => ipcRenderer.invoke('files:readImageAsBase64', filePath),
  },
  gradeDistributions: {
    getAll: () => ipcRenderer.invoke('gradeDistributions:getAll'),
    getById: (id: number) => ipcRenderer.invoke('gradeDistributions:getById', id),
    getWithCategories: (id: number) => ipcRenderer.invoke('gradeDistributions:getWithCategories', id),
    create: (data: any) => ipcRenderer.invoke('gradeDistributions:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('gradeDistributions:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('gradeDistributions:delete', id),
  },
  evaluations: {
    getByCourseId: (courseId: number) => ipcRenderer.invoke('evaluations:getByCourseId', courseId),
    getByCategoryId: (categoryId: number) => ipcRenderer.invoke('evaluations:getByCategoryId', categoryId),
    create: (data: any) => ipcRenderer.invoke('evaluations:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('evaluations:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('evaluations:delete', id),
    deleteByCourseId: (courseId: number) => ipcRenderer.invoke('evaluations:deleteByCourseId', courseId),
    copyFromCourse: (sourceCourseId: number, targetCourseId: number) => ipcRenderer.invoke('evaluations:copyFromCourse', sourceCourseId, targetCourseId),
  },
  rubrics: {
    getAll: () => ipcRenderer.invoke('rubrics:getAll'),
    getById: (id: number) => ipcRenderer.invoke('rubrics:getById', id),
    getByActivityTypeId: (activityTypeId: number) => ipcRenderer.invoke('rubrics:getByActivityTypeId', activityTypeId),
    getTemplates: () => ipcRenderer.invoke('rubrics:getTemplates'),
    create: (data: any) => ipcRenderer.invoke('rubrics:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('rubrics:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('rubrics:delete', id),
  },
  evaluationGrades: {
    getByEvaluationId: (evaluationId: number) => ipcRenderer.invoke('evaluationGrades:getByEvaluationId', evaluationId),
    getByEvaluationAndStudent: (evaluationId: number, studentId: number) => ipcRenderer.invoke('evaluationGrades:getByEvaluationAndStudent', evaluationId, studentId),
    upsert: (data: any) => ipcRenderer.invoke('evaluationGrades:upsert', data),
    delete: (evaluationId: number, studentId: number) => ipcRenderer.invoke('evaluationGrades:delete', evaluationId, studentId),
  },
  activityTypes: {
    getAll: () => ipcRenderer.invoke('activityTypes:getAll'),
    getActive: () => ipcRenderer.invoke('activityTypes:getActive'),
    getById: (id: number) => ipcRenderer.invoke('activityTypes:getById', id),
    getByEvaluationModel: (model: string) => ipcRenderer.invoke('activityTypes:getByEvaluationModel', model),
    create: (data: any) => ipcRenderer.invoke('activityTypes:create', data),
    update: (id: number, data: any) => ipcRenderer.invoke('activityTypes:update', id, data),
    delete: (id: number) => ipcRenderer.invoke('activityTypes:delete', id),
  },
  database: {
    delete: () => ipcRenderer.invoke('database:delete'),
    getPath: () => ipcRenderer.invoke('database:getPath'),
  },
});
