import type { Site } from "@domain-slayer/domain";
import type { SiteEntity } from "../entities/site.entity.js";

export function mapSiteEntityToDomain(e: SiteEntity): Site {
  return {
    id: e.id,
    siteName: e.siteName,
    businessUnit: e.businessUnit,
    domain: e.domain,
    url: e.url,
    environment: e.environment as Site["environment"],
    provider: e.provider,
    hostingProvider: e.hostingProvider,
    dnsProvider: e.dnsProvider,
    sslProvider: e.sslProvider,
    registrarProvider: e.registrarProvider,
    owner: e.owner,
    technicalOwner: e.technicalOwner,
    contactEmail: e.contactEmail,
    notes: e.notes,
    sslResolutionNotes: e.sslResolutionNotes,
    domainResolutionNotes: e.domainResolutionNotes,
    isActive: e.isActive,
    createdAt: e.createdAt,
    updatedAt: e.updatedAt,
    domainExpiryAuto: e.domainExpiryAuto,
    domainExpiryManual: e.domainExpiryManual,
    domainExpiryFinal: e.domainExpiryFinal,
    domainExpirySource: e.domainExpirySource as Site["domainExpirySource"],
    domainExpiryStatus: e.domainExpiryStatus as Site["domainExpiryStatus"],
    domainStatus: e.domainStatus as Site["domainStatus"],
    dnsStatus: e.dnsStatus as Site["dnsStatus"],
    nameserversJson: e.nameserversJson,
    aRecordsJson: e.aRecordsJson,
    aaaaRecordsJson: e.aaaaRecordsJson,
    cnameRecordsJson: e.cnameRecordsJson,
    mxRecordsJson: e.mxRecordsJson,
    soaRecordJson: e.soaRecordJson,
    httpStatus: e.httpStatus as Site["httpStatus"],
    httpsStatus: e.httpsStatus as Site["httpsStatus"],
    sslSubject: e.sslSubject,
    sslIssuer: e.sslIssuer,
    sslValidFrom: e.sslValidFrom,
    sslValidTo: e.sslValidTo,
    sslValidToManual: e.sslValidToManual,
    sslExpirySource: (e.sslExpirySource ?? "unavailable") as Site["sslExpirySource"],
    sslValidToFinal: e.sslValidToFinal,
    sslSerialNumber: e.sslSerialNumber,
    sslStatus: e.sslStatus as Site["sslStatus"],
    sslHostnameMatch: e.sslHostnameMatch,
    lastCheckedAt: e.lastCheckedAt,
    checkStatus: e.checkStatus as Site["checkStatus"],
    healthStatus: e.healthStatus as Site["healthStatus"],
  };
}
